name: Feature request
description: Suggest an idea for Relente.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Relente only supports macOS installers (Big Sur and later) and USB drives or SD cards as destinations.
  - type: textarea
    id: problem
    attributes:
      label: What problem would it solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to happen?
    validations:
      required: true
